### ISSUE TITLE
User activation settings is not possible to change

### ISSUE THREAD

**Issue by andriyun** [bellcom/os2intra_user_import#10]
When user import module user as standalone module without os2intra profile its not possible to change uer activation settings.
https://github.com/bellcom/os2intra_user_import/blob/master/os2intra_user_import.module#L111
There are no os2intra_settings_settings_form.

**Comment by andriyun** [comment]
In scope of PR #5 I've added default values to activation settings variables to get it works for Odshered

**Comment by andriyun** [comment]
@stanbellcom 
Could you handle this issue?
It's about case that we discussed yesterday morning

**Comment by stanbellcom** [comment]
PR added:
https://github.com/bellcom/os2intra_user_import/pull/11
